apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-workload-id-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudpulse.labels" . | nindent 4 }}
data:
  gcp-credentials.json: |
    {
      "type": "external_account",
      "audience": "//iam.googleapis.com/{{ .Values.costSvc.gcpProviderName }}",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/secrets/gcp/tokens/gcp-token"
      },
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/{{ .Values.costSvc.gcpServiceAccount }}:generateAccessToken"
    }
