apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudpulse-sa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudpulse.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.azureClientId | quote }}
